@extends('layouts.base')
@section('title', 'Global')
@section('content')
@include('layouts.docs-nav')<h1 class="cyan-text text-lighten-1 center-align">Global</h1>

<section>

    <header>

        <h2></h2>

    </header>

    <article>
        <div class="container-overview">

            <dl class="details"></dl>

        </div>

        <div class="container">

            <h3 class="cyan-text text-lighten-1">Methods</h3>

            <h4 class="name cyan-text text-lighten-1" id="Convert">
                <span class="type-signature "></span>Convert<span class="signature">(metadata, run)</span>
                <span class="type-signature"></span>
            </h4>

            <div class="description white-text">
                Serializes the command data.
            </div>

            <h5 class="white-text">Parameters:</h5>

            <table class="white-text">
                <thead>
                    <tr>

                        <th>Name</th>

                        <th>Type</th>

                        <th class="last">Description</th>
                    </tr>
                </thead>

                <tbody>

                    <tr>

                        <td class="name">
                            <code>metadata</code>
                        </td>

                        <td class="type">

                            <span class="param-type">Object</span>

                        </td>

                        <td class="description last">The command metadata.</td>
                    </tr>

                    <tr>

                        <td class="name">
                            <code>run</code>
                        </td>

                        <td class="type">

                            <span class="param-type">
                                <a href="VauntedCommand.html">VauntedCommand</a>
                            </span>

                        </td>

                        <td class="description last">The class for the command.</td>
                    </tr>

                    <tr>

                        <td class="name">
                            <code>metadata.name</code>
                        </td>

                        <td class="type">

                            <span class="param-type">String</span>

                        </td>

                        <td class="description last">The name and or command name for the command class.</td>
                    </tr>

                    <tr>

                        <td class="name">
                            <code>metadata.aliases</code>
                        </td>

                        <td class="type">

                            <span class="param-type">Array</span>

                        </td>

                        <td class="description last">All the aliases associated with the command.</td>
                    </tr>

                    <tr>

                        <td class="name">
                            <code>metadata.description</code>
                        </td>

                        <td class="type">

                            <span class="param-type">String</span>

                        </td>

                        <td class="description last">The description of the command.</td>
                    </tr>

                    <tr>

                        <td class="name">
                            <code>metadata.priority</code>
                        </td>

                        <td class="type">

                            <span class="param-type">Number</span>

                        </td>

                        <td class="description last">The priority of the command.</td>
                    </tr>

                </tbody>
            </table>

        </div>

    </article>

</section>


<br class="clear">

<footer class="white-text">
    Documentation generated by
    <a href="https://github.com/jsdoc/jsdoc">JSDoc 3.6.3</a>
    on Fri Oct 18 2019 20:44:24 GMT+0100 (British Summer Time)
</footer>

@endsection
<style>
        code {
          font-family: monospace;
          background-color: #23272A;
        }
        </style>
