
@extends('layouts.base')
@section ('title', 'Converter')
@section('content')
@include ('layouts.docs-nav')


<div id="main">

    <h1 class="page-title">Source: handlers/Converter.js</h1>






    <section>
        <article>
            <pre class="prettyprint source linenums"><code>/**
 * Serializes the command data.
 * @param {Object} metadata - The command metadata.
 * @param {VauntedCommand} run - The class for the command.
 *
 * @param {String} metadata.name - The name and or command name for the command class.
 * @param {Array} metadata.aliases - All the aliases associated with the command.
 * @param {String} metadata.description - The description of the command.
 * @param {Number} metadata.priority - The priority of the command.
 */
const Convert = (metadata, run) => {
    if (!run) throw new Error("You must provide a command runnable!");
    if (!metadata) throw new Error("You must provide command metadata!");
    if (!metadata.name) throw new Error("You must provide a command name!");

    const discordCommand = {
        run,
        conf: {
            aliases: metadata.aliases || []
        },
        help: {
            name: metadata.name,
            description: metadata.description || "",
            priority: metadata.priority || 1
        }
    };

    return discordCommand;
};

module.exports = Convert;</code></pre>
        </article>
    </section>




</div>

<nav>
    <h2><a href="index.html">Home</a></h2><h3>Classes</h3><ul><li><a href="CommandLoader.html">CommandLoader</a></li><li><a href="Vaunted.html">Vaunted</a></li><li><a href="VauntedCommand.html">VauntedCommand</a></li></ul><h3>Global</h3><ul><li><a href="global.html#Convert">Convert</a></li></ul>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc 3.6.3</a> on Fri Oct 18 2019 20:44:24 GMT+0100 (British Summer Time)
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
@endsection
