
@extends('layouts.base')
@section ('title', 'Home')
@section('content')
@include ('layouts.docs-nav')

<div id="main">
    <section class="center-align">
            <article><h1 class="cyan-text text-lighten-1 center-align">Vaunted</h1>
    <p class="white-text">The best Discord.js command handler</p>
    <h2 class="cyan-text text-lighten-1">Getting Started</h2>
    <p class="white-text">First of all, <a href="https://www.macworld.com/article/2042378/master-the-command-line-navigating-files-and-folders.html">cd</a> into your working directory.</p>
    <p class="white-text">After creating your node project, run the following: <code>npm install vaunted --save</code></p>
    <h2 class="cyan-text text-lighten-1">Prerequisites</h2>
    <p class="white-text">Simply run <code>npm install</code> or <code>npm i</code> to install all of the prerequisites.</p>
    <h2 class="cyan-text text-lighten-1">Documentation</h2>
    <p class="white-text">Documentation can be found <a href="https://vaunted.co.uk/documentation/">here</a></p>
    <h2 class="cyan-text text-lighten-1">Authors</h2>
    <ul>
    <li class="white-text"><strong>Kalum</strong> - <em>Initial work | Development work</em></li>
    <li class="white-text"><strong>Brad</strong> - <em>Initial work | Development work</em></li>
    <li class="white-text"><strong>Sophia</strong> - <em>Initial work | Development work</em></li>
    <li class="white-text"><strong>Jackson</strong> - <em>Rewrite | Development work</em></li>
    <li class="white-text"><strong>Alex</strong> - <em>Development work</em></li>
    </ul>
    <p class="white-text">See also the list of <a href="https://github.com/Kalum1/Vaunted/graphs/contributors">contributors</a> who participated in this project.</p>
    <h2 class="cyan-text text-lighten-1">License</h2>
    <p class="white-text">This project is licensed under the MIT License - see the <a href="LICENSE.md">LICENSE.md</a> file for details</p></article>
        </section>






</div>


<br class="clear">

<footer class="white-text">
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc 3.6.3</a> on Fri Oct 18 2019 18:03:23 GMT+0100 (British Summer Time)
</footer>

@endsection
<style>
code {
  font-family: monospace;
  background-color: #23272A;
}
</style>
