
@extends('layouts.base')
@section ('title', 'Vaunted')
@section('content')
@include ('layouts.docs-nav')


<div id="main">

    <h1 class="page-title">Source: types/Vaunted.js</h1>






    <section>
        <article>
            <pre class="prettyprint source linenums"><code>const Discord = require("discord.js");
const CommandLoader = require("../handlers/CommandLoader");

class Vaunted {
    /**
     * Creates the Vaunted Command Handler Client
     * @constructor
     * @param {String} token - Token for discord login.
     * @param {Object} options - The vaunted client options.
     */
    constructor(token, options) {
        if (!token) throw new Error("No token provided");
        if (!options.prefix) throw new Error("No prefix provided");

        this.client = new Discord.Client();
        this.token = token;
        this.options = options;

        this.commandLoader = new CommandLoader(this.client, this.options);

        this.client.on("message", msg => {
            if (this.options.ignoreBots) {
                if (msg.author.bot) return;
            };
            if (msg.content === this.options.prefix) return;
            if (!msg.content.toLowerCase().startsWith(this.options.prefix.toLowerCase())) return;

            const command = msg.content.toLowerCase().split(" ")[0].slice(this.options.prefix.length);
            const args = msg.content.split(" ").slice(1);

            const { commands, aliases } = this.client;

            let Command;
            if (commands.has(command)) {
                Command = commands.get(command);
            } else if (aliases.has(command)) {
                Command = commands.get(aliases.get(command));
            };

            if (Command) new Command.run().run(this.client, msg, args);
        });
    }

    /**
     * Logs into discord also loads commands.
     */
    login() {
        this.commandLoader.loadAllCommands();

        this.client.login(this.token);

        this.client.once("ready", () => {
            if (this.options.logging) console.log("Discord logged in!");
        });
    }
}

module.exports = Vaunted;</code></pre>
        </article>
    </section>




</div>

<nav>
    <h2><a href="index.html">Home</a></h2><h3>Classes</h3><ul><li><a href="CommandLoader.html">CommandLoader</a></li><li><a href="Vaunted.html">Vaunted</a></li><li><a href="VauntedCommand.html">VauntedCommand</a></li></ul><h3>Global</h3><ul><li><a href="global.html#Convert">Convert</a></li></ul>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc 3.6.3</a> on Fri Oct 18 2019 20:44:24 GMT+0100 (British Summer Time)
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
@endsection
