@extends('layouts.base')
@section('title', 'Main')
@section('content')
@include('layouts.docs-nav')
<div class="container">

    <h1 class="page-title cyan-text text-lighten-1 center-align">Class: Vaunted</h1>

<section>
    <header>

        <h6 class="cyan-text text-lighten-1">
            <span class="attribs">
                <span class="type-signature"></span>
            </span>Vaunted<span class="signature">(token, options)</span>
            <span class="type-signature"></span>
        </h6>

    </header>

    <article>
        <div class="container-overview white-text">

            <h4 class="name cyan-text text-lighten-1" id="Vaunted">
                <span class="type-signature"></span>new Vaunted<span class="signature">(token, options)</span>
                <span class="type-signature"></span>
            </h4>

            <div class="description">
                Creates the Vaunted Command Handler Client
            </div>

            <h5>Parameters:</h5>

            <table class="params white-text">
                <thead>
                    <tr>

                        <th>Name</th>

                        <th>Type</th>

                        <th class="last">Description</th>
                    </tr>
                </thead>

                <tbody>

                    <tr>

                        <td class="name">
                            <code>token</code>
                        </td>

                        <td class="type">

                            <span class="param-type">String</span>

                        </td>

                        <td class="description last">Token for discord login.</td>
                    </tr>

                    <tr>

                        <td class="name">
                            <code>options</code>
                        </td>

                        <td class="type">

                            <span class="param-type">Object</span>

                        </td>

                        <td class="description last">The vaunted client options.</td>
                    </tr>

                </tbody>
            </table>


        </div>

        <h3 class="subsection-title cyan-text text-lighten-1">Methods</h3>

        <h4 class="name white-text" id="login">
            <span class="type-signature"></span>login<span class="signature">()</span>
            <span class="type-signature"></span>
        </h4>

        <div class="description white-text">
            Logs into discord also loads commands.
        </div>

    </article>

</section>

<br />
</div>


<footer class="white-text">
Documentation generated by <a href = "https://github.com/jsdoc/jsdoc"> JSDoc 3.6 .3</a> on Fri Oct 18 2019 20 : 44 : 24 GMT + 0100 (
    British Summer Time
) < /footer>

@endsection
<style>
        code {
          font-family: monospace;
          background-color: #23272A;
        }
        </style>
